services:
  discovery-service:
    image: elifnidakarakas/discoveryserver
    ports:
      - 8761:8761
    mem_limit: 700m
    depends_on:
      - keycloak
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8083:8083
    mem_limit: 700m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
  api-gateway:
    image: elifnidakarakas/api-gateway
    ports:
      - 8080:8080
    mem_limit: 700m
  orderservice:
    image: elifnidakarakas/orderservice
    ports:
      - 8081:8081
    mem_limit: 700m
    depends_on:
      - postgres
  productservice:
    image: elifnidakarakas/productservice
    ports:
      - 8082:8082
    mem_limit: 700m
    depends_on:
      - mongo
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    zookeeper:
      image: confluentinc/cp-zookeeper
      ports:
        - 2181:2181
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
    kafka:
      image: confluentinc/cp-kafka
      ports:
        - 9092:9092
      environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
        KAFKA_BROKER_ID: 1
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        kafka-manager:
          image: hlebalbau/kafka-manager
          ports:
            - 9000:9000
          environment:
            ZK_HOSTS: zookeeper:2181
          depends_on:
            - kafka
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:



